### ISSUE TITLE
About point cloud to dmesh wo/ gt mesh ( ply file including vertices, faces )

### ISSUE THREAD

**Issue by swanilee** [SonSang/dmesh#6]
Hello, and thank you for the excellent research. :) 

I am currently testing code  with custom point cloud result ( w/ only vertices ) ,
I want to do an experiment with a point cloud that does not have a ground truth (GT) mesh ( w/ vertices, faces ).

After looking at Supplementary Algorithm 2, I thought it might be possible to perform reconstruction even without the GT.
However, the code seems to be written assuming the presence of a GT mesh.

Could you please provide guidance on how to proceed in the absence of a GT mesh?
And, I'm wonder if there are any plans to release the code for experiments without GT mesh.

Thank you

**Comment by SonSang** [comment]
Hi, thank you for your interest.

As you pointed out, our code can be run without GT mesh.
If you see the current implementation, you can see that the optimizer only uses the sample point positions, and optionally, their orientations:
https://github.com/SonSang/dmesh/blob/bccf17ecf014c185255159ca05657c407254fdc0/exp/2_pc_recon.py#L22

Currently, the GT mesh is used to sample those points and orientations that would be fed into the optimizer:
https://github.com/SonSang/dmesh/blob/bccf17ecf014c185255159ca05657c407254fdc0/exp/2_pc_recon.py#L659

So I believe you can use the same optimizer with only the sample points.

**Comment by swanilee** [comment]
Thank you very much for the quick reply. 😀

As you mentioned, I've confirmed that part. 
It seems that without GT , I can't use Chamfer distance-based loss, so I'm going to leave an issue.

I might have missed something, but in this case, for Chamfer distance-based loss, points sampled from the GT mesh are used for computation. Additionally, as mentioned in the paper, it also seems that, as mentioned in the paper, a point cloud composed solely of vertices cannot perform diffuse & depth rendering.

https://github.com/SonSang/dmesh/blob/bccf17ecf014c185255159ca05657c407254fdc0/exp/2_pc_recon.py#L529

There's currently no section for loading a point cloud consisting only of vertices from a "*.ply" file. In this case, how is the point cloud referenced for loss computation? Ultimately, would it be challenging to reconstruct solely based on a point cloud containing just vertices?

If I have misunderstood anything, please let me know. I would appreciate it. 🙏

**Comment by SonSang** [comment]
I'm afraid there is a small misunderstanding here.
As far as I understand, you are trying to use *.ply file, representing a point cloud, right?

In that case, you can simply set the `target_point_positions` as the points from the file here:
https://github.com/SonSang/dmesh/blob/bccf17ecf014c185255159ca05657c407254fdc0/exp/2_pc_recon.py#L22

There is no requirement for the GT mesh in the Chamfer loss computation. The Chamfer loss is computed based on the **sample points** from our current mesh and the **sample points** from the GT shape, which means that even if you do not have the GT shape, as far as you have point cloud sampled from it, you can use it as an input.

In the current implementation, I just assumed we have GT mesh so that we can compare the final reconstructed mesh and the GT mesh visually. You can definitely use point cloud input!

**Comment by swanilee** [comment]
Oh, I completely understand now. Thank you for explaining in detail! 🙌 Have a great day 😊
